
export const footer = {
  footerSlogan: "Sri Lanka's Trusted Partner in Pharmaceutical Education",
  footerHome: 'Home',
  footerAbout: 'About Us',
  footerCourses: 'Courses',
  footerContact: 'Contact',
  footerVerify: 'Verify Certificate',
  footerContactUs: 'Contact Us',
  footerEmail: 'Email: ',
  footerPhone: 'Customer Service: ',
  copyright: '© {year} Ceylon Pharma College. All Rights Reserved.',
  poweredBy: 'Powered by ',
  
  // New links
  footerPolicies: 'Our Policies',
  privacyPolicy: 'Privacy Policy',
  refundPolicy: 'Refund Policy',
  termsOfService: 'Terms of Service',
  shippingPolicy: 'Shipping Policy',
  footerCompany: 'Company',
  blogs: 'Blogs',
  event: 'Event',

  // Policy Page Content
  privacyPolicyContent: `## 1. Introduction\n\nThis Privacy Policy outlines how Ceylon Pharma College ("we", "our", or "us") collects, uses, protects, and handles your personal data when you visit our website or use our services. Your privacy is of paramount importance to us, and we are committed to safeguarding it.\n\n## 2. Information We Collect\n\nWe may collect personal identification information from Users in various ways, including, but not limited to, when Users visit our site, register on the site, place an order, subscribe to the newsletter, respond to a survey, fill out a form, and in connection with other activities, services, features or resources we make available on our Site.\n\nWe collect both personal data (such as name, email address, phone number, and mailing address) and non-personal identification information (such as browser name, type of computer, and technical information about means of connection to our Site).\n\n## 3. How We Use Collected Information\n\nCeylon Pharma College collects and uses Users personal information for the following purposes: **To improve customer service**: Information you provide helps us respond to your customer service requests and support needs more efficiently. **To personalize user experience**: We may use information in the aggregate to understand how our Users as a group use the services and resources provided on our Site.\n\n## 4. How We Protect Your Information\n\nWe adopt appropriate data collection, storage, and processing practices and security measures to protect against unauthorized access, alteration, disclosure, or destruction of your personal information, username, password, transaction information, and data stored on our Site.\n\n## 5. Sharing Your Personal Information\n\nWe do not sell, trade, or rent Users personal identification information to others. We may share generic aggregated demographic information not linked to any personal identification information regarding visitors and users with our business partners, trusted affiliates, and advertisers.\n\n## 6. Changes to This Privacy Policy\n\nCeylon Pharma College has the discretion to update this privacy policy at any time. When we do, we will revise the updated date at the bottom of this page. We encourage Users to frequently check this page for any changes to stay informed about how we are helping to protect the personal information we collect.\n\n## 7. Your Acceptance of These Terms\n\nBy using this Site, you signify your acceptance of this policy. If you do not agree to this policy, please do not use our Site. Your continued use of the Site following the posting of changes to this policy will be deemed your acceptance of those changes.`,
  refundPolicyContent: `## 1. General Refund Policy\n\nAt Ceylon Pharma College, we strive to ensure that our students receive the highest quality education. Please note that all payments made towards course fees, registration, and enrollments are strictly non-refundable under any circumstances.\n\n## 2. Non-Refundable Fees\n\nRegistration fees, admission fees, and initial enrollment deposits are strictly non-refundable, as they cover immediate administrative processing, course material allocation, and seat reservation costs. Once paid, these amounts cannot be claimed back.\n\n## 3. Mid-Course Withdrawals\n\nOnce a payment is made, no refunds will be granted even if a student decides to withdraw midway through the program or before it officially commences. Students are advised to carefully consider their availability and commitment before enrolling in any of our academic programs.\n\n## 4. Program Cancellations by the College\n\nIn the unlikely event that Ceylon Pharma College cancels a course or program prior to its commencement, enrolled students will be notified immediately. In such unique cases, students will be offered a full refund of the course fees paid or the option to transfer their enrollment to an upcoming batch.\n\n## 5. Medical Emergencies\n\nIn exceptional cases involving severe, documented medical emergencies that prevent a student from continuing their studies, the management may consider transferring the enrollment to a future intake. This is strictly at the management's sole discretion, and no cash refunds will be provided under any circumstances.`,
  termsOfServiceContent: `## 1. Acceptance of Terms\n\nWelcome to Ceylon Pharma College. These Terms of Service govern your use of our website and any related services provided by us. By accessing or using our website, you agree to be bound by these terms. If you disagree with any part of these terms and conditions, please do not use our website.\n\n## 2. Certification Policy\n\nPlease note that to be eligible to receive any course completion certificate, students must successfully complete all course requirements. This includes submitting all assignments on time, maintaining the required attendance percentage, and passing all examinations as strictly stipulated by the curriculum. Certificates will not be issued for incomplete courses.\n\n## 3. Intellectual Property Rights\n\nThe content, layout, design, data, graphics, and trademarks contained on this website are the property of Ceylon Pharma College. You may not reproduce, download, transmit, or distribute any part of this website without our explicit written consent.\n\n## 4. User Conduct\n\nWhen accessing our e-learning platforms and engaging in online discussions, you agree to conduct yourself professionally. Harassment, use of abusive language, and sharing of unauthorized copyrighted materials are strictly prohibited and may result in immediate termination of your enrollment without refund.\n\n## 5. Limitation of Liability\n\nYour use of any information or materials on this website is entirely at your own risk, for which we shall not be liable. It shall be your own responsibility to ensure that any products, services, or information available through this website meet your specific requirements. We do not provide any warranty or guarantee as to the accuracy or suitability of the information offered.\n\n## 6. Governing Law\n\nThese terms and conditions are governed by and construed in accordance with the laws of Sri Lanka. Any disputes relating to these terms and conditions will be subject to the exclusive jurisdiction of the courts of Sri Lanka.`,
  shippingPolicyContent: `## 1. Overview\n\nCeylon Pharma College primarily provides educational services and digital learning materials through our dedicated online Learning Management System (LMS). However, in instances where physical materials, such as original certificates, study guides, or promotional items, need to be delivered to students, this Shipping Policy applies.\n\n## 2. Dispatch and Processing Times\n\nAll physical documents and materials will be dispatched via registered local postal services or trusted courier partners within Sri Lanka. Processing times for dispatch may take between 3 to 7 business days after the request has been approved or a course has been successfully completed.\n\n## 3. User Responsibility\n\nStudents are strictly responsible for ensuring that the mailing address, contact number, and other relevant details provided in their student profile are accurate and up to date. Ceylon Pharma College will not be held liable for any lost, delayed, or misdirected mail resulting from incorrect address information provided by the student.\n\n## 4. International Shipping\n\nIf you require international shipping for your certificates or materials, additional shipping and handling charges will apply based on the destination country. Please contact our administration office for an estimate of international shipping fees and estimated delivery timelines before making a request.\n\n## 5. Damaged or Lost Items\n\nIf a document arrives severely damaged or is confirmed lost in transit by the courier service, please contact our support team within 14 days of the expected delivery date. We will evaluate the situation and may issue a replacement document, though reprint and shipping fees may apply depending on the circumstances.`,
};
